#!/sbin/sh

. /lib/svc/share/smf_include.sh

getproparg_optional() {
    val=`svcprop -p $1 $SMF_FMRI`
    [ -n "$val" ] && echo $val
}

getproparg_required() {
    val=`svcprop -p $1 $SMF_FMRI`
    if [ -z "$val" ]; then
        echo "Error: $1 property not set"
        exit $SMF_EXIT_ERR
	fi
    
    [ -n "$val" ] && echo $val
}

if [ -z $SMF_FMRI ]; then
        echo "Error: SMF framework variables are not initialized"
        exit $SMF_EXIT_ERR
fi

INSTANCE_NAME=`echo $SMF_FMRI | sed 's/.*:\(.*\)/\1/'`

DEVICE_CONFIG_FILE=`getproparg_required kvm/device_config_file`
MEMORY_MB=`getproparg_required kvm/memory_mb`
VCPUS=`getproparg_required kvm/vcpus`
MONITOR_FILE=`getproparg_required kvm/monitor_file`

VNC_DISPLAY=`getproparg_optional kvm/vnc_display`


sanity_check() {
	if [ ! -f $DEVICE_CONFIG_FILE ]; then
	    echo "Error: kvm/device_config_file file $DEVICE_CONFIG_FILE does not exist"
	    exit $SMF_EXIT_ERR_CONFIG
	fi
}

start_kvm() {
	VNC_ARG=""
	
	if [ -n "${VNC_DISPLAY}" ]; then
		VNC_ARG="-vnc 0.0.0.0:${VNC_DISPLAY}"
	fi
	
	/usr/bin/qemu-kvm \
		${VNC_ARG} \
		-M pc-0.14 \
		-m ${MEMORY_MB} \
		-smp ${VCPUS} \
		-name ${INSTANCE_NAME} \
		-nodefconfig \
		-nodefaults \
		-vga cirrus \
		-usb \
		-no-hpet \
		-readconfig ${DEVICE_CONFIG_FILE} \
		-enable-kvm
}

case "$1" in
'start')
        sanity_check
		start_kvm
        ;;

*)
        echo "Usage: $0 {start|stop|refresh}"
        exit 1
        ;;
esac


exit $SMF_EXIT_OK
